# Generated by Django 5.0 on 2023-12-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author_remove_article_author_article_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
