# Generated by Django 5.0 on 2023-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
