# Generated by Django 5.0 on 2024-01-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_engineer_manager_alter_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
