# Generated by Django 5.0 on 2024-02-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orderentry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
    ]
